export const ACTIONS = {
  OPEN_USER_INFO_MODAL: "OPEN_USER_INFO_MODAL",
  OPEN_USER_ROOTS_MODAL: "OPEN_USER_ROOTS_MODAL",
  SEARCH_BY_WTMID: "SEARCH_BY_WTMID",
};

export const MODALS = {
  USER_INFO: "USER_INFO",
  SEARCH_BY_NAGRA: "SEARCH_BY_NAGRA",
  USER_ROOTS: "USER_ROOTS",
  MESH: "MESH",
};

export const MONITORS = {
  HASH: "HashMonitor",
  IP: "IpMonitor",
  USER: "UserMonitor",
};
